name: Build and Publish .NET App

on:
  workflow_dispatch:   # Voit käynnistää käsin GitHubin UI:sta

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      # Kloonaa repo
      - uses: actions/checkout@v4

      # Asenna oikea .NET-versio (muokkaa tarvittaessa)
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Käännä projekti (päivitä .sln-tiedoston nimi omasi mukaan)
      - name: Build
        run: dotnet build TimeTracker.sln --configuration Release

      # Publisoi julkaisuvalmiit tiedostot (päivitä polku omaksi!)
      - name: Publish
        run: dotnet publish ./TimeTracker.csproj -c Release -o ./publish

      - name: Zip published files
        run: Compress-Archive -Path publish\* -DestinationPath publish.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-zip
          path: publish.zip
